// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: magic_tunnel/remote_config/remote_config.proto

package remoteconfigv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Magic Tunnel request payloads for the `REMOTE_CONFIG` namespace.
type RemoteConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Subtopic:
	//
	//	*RemoteConfigRequest_FlareRequest
	Subtopic      isRemoteConfigRequest_Subtopic `protobuf_oneof:"subtopic"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteConfigRequest) Reset() {
	*x = RemoteConfigRequest{}
	mi := &file_magic_tunnel_remote_config_remote_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteConfigRequest) ProtoMessage() {}

func (x *RemoteConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_magic_tunnel_remote_config_remote_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteConfigRequest.ProtoReflect.Descriptor instead.
func (*RemoteConfigRequest) Descriptor() ([]byte, []int) {
	return file_magic_tunnel_remote_config_remote_config_proto_rawDescGZIP(), []int{0}
}

func (x *RemoteConfigRequest) GetSubtopic() isRemoteConfigRequest_Subtopic {
	if x != nil {
		return x.Subtopic
	}
	return nil
}

func (x *RemoteConfigRequest) GetFlareRequest() *FlareRequest {
	if x != nil {
		if x, ok := x.Subtopic.(*RemoteConfigRequest_FlareRequest); ok {
			return x.FlareRequest
		}
	}
	return nil
}

type isRemoteConfigRequest_Subtopic interface {
	isRemoteConfigRequest_Subtopic()
}

type RemoteConfigRequest_FlareRequest struct {
	FlareRequest *FlareRequest `protobuf:"bytes,1,opt,name=flare_request,json=flareRequest,proto3,oneof"`
}

func (*RemoteConfigRequest_FlareRequest) isRemoteConfigRequest_Subtopic() {}

// Response payloads for `RemoteConfigRequest` calls.
type RemoteConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Subtopic:
	//
	//	*RemoteConfigResponse_FlareResponse
	Subtopic      isRemoteConfigResponse_Subtopic `protobuf_oneof:"subtopic"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteConfigResponse) Reset() {
	*x = RemoteConfigResponse{}
	mi := &file_magic_tunnel_remote_config_remote_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteConfigResponse) ProtoMessage() {}

func (x *RemoteConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_magic_tunnel_remote_config_remote_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteConfigResponse.ProtoReflect.Descriptor instead.
func (*RemoteConfigResponse) Descriptor() ([]byte, []int) {
	return file_magic_tunnel_remote_config_remote_config_proto_rawDescGZIP(), []int{1}
}

func (x *RemoteConfigResponse) GetSubtopic() isRemoteConfigResponse_Subtopic {
	if x != nil {
		return x.Subtopic
	}
	return nil
}

func (x *RemoteConfigResponse) GetFlareResponse() *FlareResponse {
	if x != nil {
		if x, ok := x.Subtopic.(*RemoteConfigResponse_FlareResponse); ok {
			return x.FlareResponse
		}
	}
	return nil
}

type isRemoteConfigResponse_Subtopic interface {
	isRemoteConfigResponse_Subtopic()
}

type RemoteConfigResponse_FlareResponse struct {
	FlareResponse *FlareResponse `protobuf:"bytes,1,opt,name=flare_response,json=flareResponse,proto3,oneof"`
}

func (*RemoteConfigResponse_FlareResponse) isRemoteConfigResponse_Subtopic() {}

// Request the agent return gather and return troubleshooting data to Datadog
// servers - an "Agent Flare":
//
//	https://docs.datadoghq.com/agent/troubleshooting/send_a_flare/?tab=agent
type FlareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UserHandle    string                 `protobuf:"bytes,2,opt,name=user_handle,json=userHandle,proto3" json:"user_handle,omitempty"`
	CaseId        uint64                 `protobuf:"varint,3,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlareRequest) Reset() {
	*x = FlareRequest{}
	mi := &file_magic_tunnel_remote_config_remote_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlareRequest) ProtoMessage() {}

func (x *FlareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_magic_tunnel_remote_config_remote_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlareRequest.ProtoReflect.Descriptor instead.
func (*FlareRequest) Descriptor() ([]byte, []int) {
	return file_magic_tunnel_remote_config_remote_config_proto_rawDescGZIP(), []int{2}
}

func (x *FlareRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *FlareRequest) GetUserHandle() string {
	if x != nil {
		return x.UserHandle
	}
	return ""
}

func (x *FlareRequest) GetCaseId() uint64 {
	if x != nil {
		return x.CaseId
	}
	return 0
}

type FlareResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The zip archive containing the flare data.
	ZipArchive    []byte `protobuf:"bytes,1,opt,name=zip_archive,json=zipArchive,proto3" json:"zip_archive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlareResponse) Reset() {
	*x = FlareResponse{}
	mi := &file_magic_tunnel_remote_config_remote_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlareResponse) ProtoMessage() {}

func (x *FlareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_magic_tunnel_remote_config_remote_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlareResponse.ProtoReflect.Descriptor instead.
func (*FlareResponse) Descriptor() ([]byte, []int) {
	return file_magic_tunnel_remote_config_remote_config_proto_rawDescGZIP(), []int{3}
}

func (x *FlareResponse) GetZipArchive() []byte {
	if x != nil {
		return x.ZipArchive
	}
	return nil
}

var File_magic_tunnel_remote_config_remote_config_proto protoreflect.FileDescriptor

const file_magic_tunnel_remote_config_remote_config_proto_rawDesc = "" +
	"\n" +
	".magic_tunnel/remote_config/remote_config.proto\x12%rc.x509.magic_tunnel.remote_config.v1\"}\n" +
	"\x13RemoteConfigRequest\x12Z\n" +
	"\rflare_request\x18\x01 \x01(\v23.rc.x509.magic_tunnel.remote_config.v1.FlareRequestH\x00R\fflareRequestB\n" +
	"\n" +
	"\bsubtopic\"\x81\x01\n" +
	"\x14RemoteConfigResponse\x12]\n" +
	"\x0eflare_response\x18\x01 \x01(\v24.rc.x509.magic_tunnel.remote_config.v1.FlareResponseH\x00R\rflareResponseB\n" +
	"\n" +
	"\bsubtopic\"\\\n" +
	"\fFlareRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1f\n" +
	"\vuser_handle\x18\x02 \x01(\tR\n" +
	"userHandle\x12\x17\n" +
	"\acase_id\x18\x03 \x01(\x04R\x06caseId\"0\n" +
	"\rFlareResponse\x12\x1f\n" +
	"\vzip_archive\x18\x01 \x01(\fR\n" +
	"zipArchiveB\\ZZgithub.com/DataDog/libdd-rc/ffi-hosts/go/rcproto/magic_tunnel/remote_config;remoteconfigv1b\x06proto3"

var (
	file_magic_tunnel_remote_config_remote_config_proto_rawDescOnce sync.Once
	file_magic_tunnel_remote_config_remote_config_proto_rawDescData []byte
)

func file_magic_tunnel_remote_config_remote_config_proto_rawDescGZIP() []byte {
	file_magic_tunnel_remote_config_remote_config_proto_rawDescOnce.Do(func() {
		file_magic_tunnel_remote_config_remote_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_magic_tunnel_remote_config_remote_config_proto_rawDesc), len(file_magic_tunnel_remote_config_remote_config_proto_rawDesc)))
	})
	return file_magic_tunnel_remote_config_remote_config_proto_rawDescData
}

var file_magic_tunnel_remote_config_remote_config_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_magic_tunnel_remote_config_remote_config_proto_goTypes = []any{
	(*RemoteConfigRequest)(nil),  // 0: rc.x509.magic_tunnel.remote_config.v1.RemoteConfigRequest
	(*RemoteConfigResponse)(nil), // 1: rc.x509.magic_tunnel.remote_config.v1.RemoteConfigResponse
	(*FlareRequest)(nil),         // 2: rc.x509.magic_tunnel.remote_config.v1.FlareRequest
	(*FlareResponse)(nil),        // 3: rc.x509.magic_tunnel.remote_config.v1.FlareResponse
}
var file_magic_tunnel_remote_config_remote_config_proto_depIdxs = []int32{
	2, // 0: rc.x509.magic_tunnel.remote_config.v1.RemoteConfigRequest.flare_request:type_name -> rc.x509.magic_tunnel.remote_config.v1.FlareRequest
	3, // 1: rc.x509.magic_tunnel.remote_config.v1.RemoteConfigResponse.flare_response:type_name -> rc.x509.magic_tunnel.remote_config.v1.FlareResponse
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_magic_tunnel_remote_config_remote_config_proto_init() }
func file_magic_tunnel_remote_config_remote_config_proto_init() {
	if File_magic_tunnel_remote_config_remote_config_proto != nil {
		return
	}
	file_magic_tunnel_remote_config_remote_config_proto_msgTypes[0].OneofWrappers = []any{
		(*RemoteConfigRequest_FlareRequest)(nil),
	}
	file_magic_tunnel_remote_config_remote_config_proto_msgTypes[1].OneofWrappers = []any{
		(*RemoteConfigResponse_FlareResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_magic_tunnel_remote_config_remote_config_proto_rawDesc), len(file_magic_tunnel_remote_config_remote_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_magic_tunnel_remote_config_remote_config_proto_goTypes,
		DependencyIndexes: file_magic_tunnel_remote_config_remote_config_proto_depIdxs,
		MessageInfos:      file_magic_tunnel_remote_config_remote_config_proto_msgTypes,
	}.Build()
	File_magic_tunnel_remote_config_remote_config_proto = out.File
	file_magic_tunnel_remote_config_remote_config_proto_goTypes = nil
	file_magic_tunnel_remote_config_remote_config_proto_depIdxs = nil
}
