// Messages for the opening connection handshake.

syntax = "proto3";
package rc.x509.protocol.v1;

import "protocol/connection_id.proto";

option go_package = "github.com/DataDog/libdd-rc/ffi-hosts/go/rcproto/protocol;protocolv1";

// A `ClientHello` is the opening message sent by the client to the delivery
// backend once a connection is established.
message ClientHello {
  // A 128-bit / 16-byte cryptographically secure random value, never reused.
  //
  // The security of the protocol relies on the uniqueness and randomness of
  // this value.
  bytes nonce = 1;

  // The number of times this client instance has been gracefully disconnected
  // from the RC backend by the RC server.
  uint64 graceful_disconnection_count = 2;

  // The number of times this client instance has been forcibly / ungracefully
  // disconnected from the RC backend.
  uint64 ungraceful_disconnection_count = 3;

  // Opaque data previously provided by the server by a `SetReconnectionData`
  // message, or an empty payload if none has been previously set.
  //
  // This data is opaque to the client; it MUST NOT change this data in any way.
  bytes reconnection_data = 4;

  // Client build version information.
  //
  // semver major number.
  uint32 version_major = 5;
  // Client version: semver minor number.
  uint32 version_minor = 6;
  // Client version: semver patch number.
  uint32 version_patch = 7;
  // Client version: optional pre-release string.
  optional string version_pre = 8;

  // Client version: Git commit hash for client build.
  string version_commit = 9;

  // A friendly, descriptive name that identifies the application that is
  // connecting (e.g. "Datadog Agent").
  string app_name = 10;

  // The duration the most recently closed remained connected, if any.
  uint64 last_closed_connection_duration_seconds = 11;
}

// A `ClientHelloAck` is the response to a `ClientHello` to complete the
// opening connection handshake.
message ClientHelloAck {
  // The unique, random ID for this connection.
  //
  // This ID is derived by generating the following hash:
  //
  // ```text
  //    h := sha256(ClientHelloAck.server_nonce + ClientHello.nonce)
  //    id := trunc(h, 128 bits)
  // ```
  //
  // And converting the 16-byte truncated `id` into a UUIDv8, as described in
  // [RFC 9562 § B.2].
  //
  // Clients MUST verify the final connection ID incorporated the client nonce
  // sent in the opening `ClientHello` message.
  //
  // [RFC 9562 § B.2]:
  //     https://www.rfc-editor.org/rfc/rfc9562.html#uuidv8_example_name
  ConnectionId connection_id = 1;

  // The server nonce used to derive the connection ID.
  bytes server_nonce = 2;
}

// Opaque data to present to the server if this client instance is later forced
// to reconnect.
//
// This data is used to speed up connection reinitialisation after a disconnect.
message SetReconnectionData {
  // The reconnection data.
  //
  // This data is opaque to the client; it MUST NOT change this data in any way.
  bytes opaque = 1;
}
