// Graceful disconnect notification.

syntax = "proto3";
package rc.x509.protocol.v1;

option go_package = "github.com/DataDog/libdd-rc/ffi-hosts/go/rcproto/protocol;protocolv1";

// The client is disconnecting due to a protocol error.
//
// This typically caused by the server sending a protocol message that is
// unexpected for the current client state.
//
// Upon receipt of a ClientProtocolError, the server MUST close the connection.
message ClientProtocolError {
  // The server has sent a ClientHelloAck before the client has sent the
  // ClientHello handshake message.
  message HandshakeAckBeforeHello {}

  // The server has sent a ClientHelloAck after the client had previously
  // marked the handshake as complete.
  message HandshakeDuplicateAck {}

  // The connection ID proposed by the server cannot be verified to have been
  // derived from the client nonce, and therefore cannot be trusted as unique
  // for this client.
  //
  // See the ConnectionId proto type docs for more info.
  message HandshakeConnectionIdRejected {}

  // The protobuf wire representation could not be deserialised.
  //
  // This either means the wire data was corrupt when it reached the client
  // library, or a message type was sent to the client that is not aware of a
  // new addition (breaking protobuf change).
  message DeserialisationFailed {}

  // The reported protocol error, including error-specific context if
  // appropriate.
  oneof error {
    HandshakeAckBeforeHello handshake_ack_before_hello = 1;
    HandshakeDuplicateAck handshake_duplicate_ack = 2;
    HandshakeConnectionIdRejected handshake_connection_id_rejected = 3;
    DeserialisationFailed deserialisation_failed = 4;
  }

  // True if the client believes the handshake has completed successfully
  // prior to raising this error.
  bool is_handshake_complete = 5;
}