// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: magic_tunnel/protocol.proto

// This package contains the wire types for the Magic Tunnel feature.

package magictunnelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A `Namespace` specifies which handler receives the payload being transmitted
// to the Agent (or other clients of RC).
//
// The primary purpose of a `Namespace` is to isolate across different teams /
// products / features supported by Magic Tunnel or other future features,
// directing payloads to the appropriate namespace handler.
//
// A namespace handler can register to receive messages from multiple
// namespaces, but a namespace can have at most one handler (consider internal
// fanout within the handler if necessary).
//
// ```text
//
//	                             Datadog Server
//
//	                                    │
//	                                    ▼
//	                         ┌────────────────────┐
//	                         │     RC Client      │
//	                         └────────────────────┘
//	                                    │
//	                              Magic │ Tunnel
//	                                    │
//	  ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┼ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─
//	D                                   │                                 D
//	I          Namespace:               │                Namespace:       I
//	S             Bananas  ┌────────────┴─────────────┐  Platanos         S
//	P                      ▼                          ▼                   P
//	A           ┌────────────────────┐     ┌────────────────────┐         A
//	T           │    Team Bananas    │     │   Team Platanos    │         T
//	C           └────────────────────┘     └────────────────────┘         C
//	H                      │                          │                   H
//	  ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─│─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┼ ─ ─ ─ ─ ─ ─ ─ ─ ─
//	                       │                          │
//	                ┌──────┴───┐                      │
//	                │          ▼                      ▼
//	      Subtopic: │   ┌────────────┐         ┌────────────┐
//	     Function A │   │ Function B │         │ Functions  ├┐
//	                ▼   └────────────┘         └┬───────────┘│
//	         ┌────────────┐                     └────────────┘
//	         │ Function A │
//	         └────────────┘
//
// ```
//
// Once a payload is routed to the correct namespace handler, it is the
// responsibility of the namespace handler to discriminate across appropriate
// subtopics, if any.
//
// This enum SHOULD contain an entry for high level, product / team namespaces
// only; it SHOULD NOT contain an entry for each payload type supported by a
// team / product (define subtopics instead).
type Namespace int32

const (
	Namespace_NAMESPACE_UNSPECIFIED   Namespace = 0
	Namespace_NAMESPACE_REMOTE_CONFIG Namespace = 1
)

// Enum value maps for Namespace.
var (
	Namespace_name = map[int32]string{
		0: "NAMESPACE_UNSPECIFIED",
		1: "NAMESPACE_REMOTE_CONFIG",
	}
	Namespace_value = map[string]int32{
		"NAMESPACE_UNSPECIFIED":   0,
		"NAMESPACE_REMOTE_CONFIG": 1,
	}
)

func (x Namespace) Enum() *Namespace {
	p := new(Namespace)
	*p = x
	return p
}

func (x Namespace) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Namespace) Descriptor() protoreflect.EnumDescriptor {
	return file_magic_tunnel_protocol_proto_enumTypes[0].Descriptor()
}

func (Namespace) Type() protoreflect.EnumType {
	return &file_magic_tunnel_protocol_proto_enumTypes[0]
}

func (x Namespace) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Namespace.Descriptor instead.
func (Namespace) EnumDescriptor() ([]byte, []int) {
	return file_magic_tunnel_protocol_proto_rawDescGZIP(), []int{0}
}

// Push a payload down to a namespace handler.
type MagicTunnelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The namespace this payload will be delivered to.
	Namespace Namespace `protobuf:"varint,2,opt,name=namespace,proto3,enum=rc.x509.magic_tunnel.v1.Namespace" json:"namespace,omitempty"`
	// The protobuf-serialised payload bytes to pass to the namespace handler for
	// this namespace.
	//
	// Payloads MUST internally discriminate across subtopics. The recommended way
	// to implement subtopics is to use a oneof:
	//
	// ```protobuf
	//
	//	message TeamBananasRequest {
	//	  oneof subtopic {
	//	    Ping ping_request = 1;
	//	    Exec exec_request = 2;
	//	    // etc...
	//	  }
	//	}
	//
	// ```
	//
	// This provides a well-typed payload structure and allows future extension of
	// the payload for this namespace in a backwards compatible way.
	Payload       []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MagicTunnelRequest) Reset() {
	*x = MagicTunnelRequest{}
	mi := &file_magic_tunnel_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MagicTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MagicTunnelRequest) ProtoMessage() {}

func (x *MagicTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_magic_tunnel_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MagicTunnelRequest.ProtoReflect.Descriptor instead.
func (*MagicTunnelRequest) Descriptor() ([]byte, []int) {
	return file_magic_tunnel_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *MagicTunnelRequest) GetNamespace() Namespace {
	if x != nil {
		return x.Namespace
	}
	return Namespace_NAMESPACE_UNSPECIFIED
}

func (x *MagicTunnelRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// A response to a MagicTunnelRequest.
type MagicTunnelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*MagicTunnelResponse_Response
	//	*MagicTunnelResponse_HandlerError
	Result        isMagicTunnelResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MagicTunnelResponse) Reset() {
	*x = MagicTunnelResponse{}
	mi := &file_magic_tunnel_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MagicTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MagicTunnelResponse) ProtoMessage() {}

func (x *MagicTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_magic_tunnel_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MagicTunnelResponse.ProtoReflect.Descriptor instead.
func (*MagicTunnelResponse) Descriptor() ([]byte, []int) {
	return file_magic_tunnel_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *MagicTunnelResponse) GetResult() isMagicTunnelResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *MagicTunnelResponse) GetResponse() []byte {
	if x != nil {
		if x, ok := x.Result.(*MagicTunnelResponse_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *MagicTunnelResponse) GetHandlerError() string {
	if x != nil {
		if x, ok := x.Result.(*MagicTunnelResponse_HandlerError); ok {
			return x.HandlerError
		}
	}
	return ""
}

type isMagicTunnelResponse_Result interface {
	isMagicTunnelResponse_Result()
}

type MagicTunnelResponse_Response struct {
	// The response payload returned by the namespace handler, which may be a
	// structured error.
	//
	// Like the request payload, this value MUST be internally discriminated by
	// subtopic.
	Response []byte `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

type MagicTunnelResponse_HandlerError struct {
	// The namespace handler implementation returned an execution error.
	//
	// This is returned to the backend for debugging and logging purposes.
	// Integrations SHOULD NOT parse this string (or any error string) to
	// classify failures. Instead prefer returning a response payload that
	// contains a structured error response.
	HandlerError string `protobuf:"bytes,4,opt,name=handler_error,json=handlerError,proto3,oneof"`
}

func (*MagicTunnelResponse_Response) isMagicTunnelResponse_Result() {}

func (*MagicTunnelResponse_HandlerError) isMagicTunnelResponse_Result() {}

var File_magic_tunnel_protocol_proto protoreflect.FileDescriptor

const file_magic_tunnel_protocol_proto_rawDesc = "" +
	"\n" +
	"\x1bmagic_tunnel/protocol.proto\x12\x17rc.x509.magic_tunnel.v1\"p\n" +
	"\x12MagicTunnelRequest\x12@\n" +
	"\tnamespace\x18\x02 \x01(\x0e2\".rc.x509.magic_tunnel.v1.NamespaceR\tnamespace\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"d\n" +
	"\x13MagicTunnelResponse\x12\x1c\n" +
	"\bresponse\x18\x02 \x01(\fH\x00R\bresponse\x12%\n" +
	"\rhandler_error\x18\x04 \x01(\tH\x00R\fhandlerErrorB\b\n" +
	"\x06result*C\n" +
	"\tNamespace\x12\x19\n" +
	"\x15NAMESPACE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17NAMESPACE_REMOTE_CONFIG\x10\x01BMZKgithub.com/DataDog/libdd-rc/ffi-hosts/go/rcproto/magic_tunnel;magictunnelv1b\x06proto3"

var (
	file_magic_tunnel_protocol_proto_rawDescOnce sync.Once
	file_magic_tunnel_protocol_proto_rawDescData []byte
)

func file_magic_tunnel_protocol_proto_rawDescGZIP() []byte {
	file_magic_tunnel_protocol_proto_rawDescOnce.Do(func() {
		file_magic_tunnel_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_magic_tunnel_protocol_proto_rawDesc), len(file_magic_tunnel_protocol_proto_rawDesc)))
	})
	return file_magic_tunnel_protocol_proto_rawDescData
}

var file_magic_tunnel_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_magic_tunnel_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_magic_tunnel_protocol_proto_goTypes = []any{
	(Namespace)(0),              // 0: rc.x509.magic_tunnel.v1.Namespace
	(*MagicTunnelRequest)(nil),  // 1: rc.x509.magic_tunnel.v1.MagicTunnelRequest
	(*MagicTunnelResponse)(nil), // 2: rc.x509.magic_tunnel.v1.MagicTunnelResponse
}
var file_magic_tunnel_protocol_proto_depIdxs = []int32{
	0, // 0: rc.x509.magic_tunnel.v1.MagicTunnelRequest.namespace:type_name -> rc.x509.magic_tunnel.v1.Namespace
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_magic_tunnel_protocol_proto_init() }
func file_magic_tunnel_protocol_proto_init() {
	if File_magic_tunnel_protocol_proto != nil {
		return
	}
	file_magic_tunnel_protocol_proto_msgTypes[1].OneofWrappers = []any{
		(*MagicTunnelResponse_Response)(nil),
		(*MagicTunnelResponse_HandlerError)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_magic_tunnel_protocol_proto_rawDesc), len(file_magic_tunnel_protocol_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_magic_tunnel_protocol_proto_goTypes,
		DependencyIndexes: file_magic_tunnel_protocol_proto_depIdxs,
		EnumInfos:         file_magic_tunnel_protocol_proto_enumTypes,
		MessageInfos:      file_magic_tunnel_protocol_proto_msgTypes,
	}.Build()
	File_magic_tunnel_protocol_proto = out.File
	file_magic_tunnel_protocol_proto_goTypes = nil
	file_magic_tunnel_protocol_proto_depIdxs = nil
}
