syntax = "proto3";

// Magic tunnel protocol message types.
//
// Each message sent over the Magic Tunnel is defined by the fully-qualified
// gRPC method URI that was used to trigger the request.
// 
// For example, the example `DebugService` for the Remote Config team has a
// method called `Ping` which has a fully qualified name of:
//
// ```text
// rc.x509.magic_tunnel.remote_config.v1.DebugService/Ping
// ```
//
// This both isolates across different teams / products / features supported by
// Magic Tunnel, and directs payloads to the appropriate method handler.
//
// ```text
//                                                                            
//                               Datadog Server                               
//                                                                            
//                                      │                                     
//                                      ▼                                     
//                           ┌────────────────────┐                           
//                           │     RC Client      │                           
//                           └────────────────────┘                           
//                                      │                                     
//                                      │                                     
//                                Magic │ Tunnel                              
//                                      │                                     
//    ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┼ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   
//   D           rc.x509.               │                                  D  
//   I      magic_tunnel.               │                                  I  
//   S   remote_config.v1  ┌────────────┴─────────────┐                    S  
//   P                     ▼                          ▼                    P  
//   A          ┌────────────────────┐     ┌────────────────────┐          A  
//   T          │ DebugService/Ping  │     │OtherService/Bananas│          T  
//   C          └────────────────────┘     └────────────────────┘          C  
//   H                     │                          │                    H  
//    ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─│─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┼ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   
//                         │                          │                       
//                         ▼                          ▼                       
//                   ┌───────────┐              ┌───────────┐                 
//                   │  Handler  │              │  Handler  │                 
//                   └───────────┘              └───────────┘                 
// ```
//
package rc.x509.magic_tunnel.v1;

option go_package = "github.com/DataDog/libdd-rc/ffi-hosts/go/rcproto/magic_tunnel;magictunnelv1";

// Push a request payload down to a request handler.
message MagicTunnelRequest {
  // The fully-qualified method name used to trigger this request.
  //
  // Example: `rc.x509.magic_tunnel.remote_config.v1.DebugService/Ping`
  string uri = 1;

  // The serialised protobuf request payload of the correct type for this URI.
  bytes request = 2;
}

// A response to a MagicTunnelRequest.
message MagicTunnelResponse {
  oneof result {
    // The response payload returned by the handler, which may be an
    // application-defined structured error.
    //
    // The serialised protobuf response payload of the correct type for this
    // URI.
    bytes response = 1;

    // The handler implementation returned an execution error.
    //
    // This is returned to the backend for debugging and logging purposes.
    // Integrations SHOULD NOT parse this string (or any error string) to
    // classify failures. Instead prefer returning a response payload that
    // contains a structured error response.
    string handler_error = 2;
  }
}
