syntax = "proto3";
package rc.x509.magic_tunnel.remote_config.v1;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/DataDog/libdd-rc/ffi-hosts/go/rcproto/magic_tunnel/remote_config;remoteconfigv1";

// Magic Tunnel request payloads for the `REMOTE_CONFIG` namespace.
message RemoteConfigRequest {
  oneof subtopic {
    // "Ping" the host application, through the dispatch interface to verify
    // end-to-end functionality.
    PingRequest ping = 1;
  }
}

// Response payloads for `RemoteConfigRequest` calls.
message RemoteConfigResponse {
  oneof subtopic {
    PingResponse ping_response = 1;
  }
}

message PingRequest {
  // The Connection ID of the client to ping.
  string connection_id = 1;

  // A reason for the ping, logged on the client.
  string reason = 2;

  // Some opaque payload the client should return (e.g. to measure approximate
  // bandwidth by sending a known size payload and recording the response time).
  bytes payload = 3;
}

message PingResponse {
  // The current timestamp as reported by the client.
  google.protobuf.Timestamp now = 1;
}
