syntax = "proto3";
package rc.x509.magic_tunnel.remote_config.v1;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/DataDog/libdd-rc/ffi-hosts/go/rcproto/magic_tunnel/remote_config;remoteconfigv1";

// A debug service for the Remote Config team to interact with the platform and
// connected clients.
service DebugService {
  // Ping the specified client by connection ID.
  rpc Ping(PingRequest) returns (PingResponse);
}

// "Ping" a specific client.
message PingRequest {
  // The Connection ID of the client to ping.
  string connection_id = 1;

  // A reason for the ping, logged on the client.
  string reason = 2;

  // Some opaque payload the client should return (e.g. to measure approximate
  // bandwidth by sending a known size payload and recording the response time).
  bytes payload = 3;
}

// Return a "pong" to a "ping".
message PingResponse {
  // The current timestamp as reported by the client.
  google.protobuf.Timestamp now = 1;
}

// Magic Tunnel request payloads for the `REMOTE_CONFIG` namespace.
//
// This is the encoded type that is emitted by the client library. It must
// contain one entry per RPC.
message DebugServiceRequest {
  oneof subtopic {
    // "Ping" the host application, through the dispatch interface to verify
    // end-to-end functionality.
    PingRequest ping = 1;
  }
}

// Response payloads for `DebugServiceRequest` calls.
//
// See DebugServiceRequest.
message DebugServiceResponse {
  oneof subtopic {
    PingResponse ping = 1;
  }
}
