# Copyright 2026-Present Datadog, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "rc-x509-test-client-harness"

# Match the rc-x509-client version below!
#
# Keeping them in-sync will let us target specific client versions when
# importing this library in other systems.
version = "0.2.0"

edition.workspace = true
license.workspace = true
description = "Test harness for exercising the RC X509 client library"
repository = "https://github.com/DataDog/libdd-rc"

[lints]
workspace = true

[dependencies]
# Keep the '=' prefix in the version, pinning to an exact version.
rc-x509-client = { version = "=0.2.0", path = "../rc-x509-client" }

assert_matches = "1.5.0"
rc-crypto = { version = "0.1.1", path = "../rc-crypto" }
rc-x509-proto = { version = "0.2.0", path = "../rc-x509-proto" }
tokio = { version = "1.52.3", features = ["rt", "sync", "time"] }
tokio-stream = "0.1.18"
tokio-util = "0.7.18"
tracing-subscriber = { version = "0.3.23", features = ["fmt", "env-filter"] }
