// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: protocol.proto

package testproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages from the RC backend server, to an RC client.
type ServerToClient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerToClient_Ping
	//	*ServerToClient_CertificatePush
	Message       isServerToClient_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerToClient) Reset() {
	*x = ServerToClient{}
	mi := &file_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerToClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerToClient) ProtoMessage() {}

func (x *ServerToClient) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerToClient.ProtoReflect.Descriptor instead.
func (*ServerToClient) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *ServerToClient) GetMessage() isServerToClient_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerToClient) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Message.(*ServerToClient_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ServerToClient) GetCertificatePush() *Certificate {
	if x != nil {
		if x, ok := x.Message.(*ServerToClient_CertificatePush); ok {
			return x.CertificatePush
		}
	}
	return nil
}

type isServerToClient_Message interface {
	isServerToClient_Message()
}

type ServerToClient_Ping struct {
	Ping *Ping `protobuf:"bytes,1,opt,name=ping,proto3,oneof"`
}

type ServerToClient_CertificatePush struct {
	// The server is pushing a new X509 certificate to the client to consider
	// when chain building.
	//
	// This certificate MUST be treated as an untrusted input.
	CertificatePush *Certificate `protobuf:"bytes,2,opt,name=certificate_push,json=certificatePush,proto3,oneof"`
}

func (*ServerToClient_Ping) isServerToClient_Message() {}

func (*ServerToClient_CertificatePush) isServerToClient_Message() {}

// Messages from an RC client, to the RC backend server.
type ClientToServer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ClientToServer_Pong
	//	*ClientToServer_ClientHello
	Message       isClientToServer_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientToServer) Reset() {
	*x = ClientToServer{}
	mi := &file_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientToServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientToServer) ProtoMessage() {}

func (x *ClientToServer) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientToServer.ProtoReflect.Descriptor instead.
func (*ClientToServer) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *ClientToServer) GetMessage() isClientToServer_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ClientToServer) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Message.(*ClientToServer_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *ClientToServer) GetClientHello() *ClientHello {
	if x != nil {
		if x, ok := x.Message.(*ClientToServer_ClientHello); ok {
			return x.ClientHello
		}
	}
	return nil
}

type isClientToServer_Message interface {
	isClientToServer_Message()
}

type ClientToServer_Pong struct {
	Pong *Pong `protobuf:"bytes,1,opt,name=pong,proto3,oneof"`
}

type ClientToServer_ClientHello struct {
	ClientHello *ClientHello `protobuf:"bytes,2,opt,name=client_hello,json=clientHello,proto3,oneof"`
}

func (*ClientToServer_Pong) isClientToServer_Message() {}

func (*ClientToServer_ClientHello) isClientToServer_Message() {}

// An application-level ping message.
//
// While the WebSocket transport to the RC delivery backend has a transport
// level "ping" control frame, it doesn't capture the full end-to-end delivery
// path as it never transits through the client library.
//
// This application-level ping frame arrives as a standard message to the client
// library, and transits through the FFI layer in addition to the WebSocket
// transport.
//
// This message is useful for ensuring the client is still alive, in addition to
// the WebSocket connection.
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{2}
}

// The response to a `Ping` message from the server.
type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{3}
}

type ClientHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{4}
}

// An X509 certificate as raw DER-encoded bytes.
type Certificate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Der           []byte                 `protobuf:"bytes,1,opt,name=der,proto3" json:"der,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Certificate) Reset() {
	*x = Certificate{}
	mi := &file_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate) ProtoMessage() {}

func (x *Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certificate.ProtoReflect.Descriptor instead.
func (*Certificate) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *Certificate) GetDer() []byte {
	if x != nil {
		return x.Der
	}
	return nil
}

var File_protocol_proto protoreflect.FileDescriptor

const file_protocol_proto_rawDesc = "" +
	"\n" +
	"\x0eprotocol.proto\x12\x13rc.x509.protocol.v1\"\x9b\x01\n" +
	"\x0eServerToClient\x12/\n" +
	"\x04ping\x18\x01 \x01(\v2\x19.rc.x509.protocol.v1.PingH\x00R\x04ping\x12M\n" +
	"\x10certificate_push\x18\x02 \x01(\v2 .rc.x509.protocol.v1.CertificateH\x00R\x0fcertificatePushB\t\n" +
	"\amessage\"\x93\x01\n" +
	"\x0eClientToServer\x12/\n" +
	"\x04pong\x18\x01 \x01(\v2\x19.rc.x509.protocol.v1.PongH\x00R\x04pong\x12E\n" +
	"\fclient_hello\x18\x02 \x01(\v2 .rc.x509.protocol.v1.ClientHelloH\x00R\vclientHelloB\t\n" +
	"\amessage\"\x06\n" +
	"\x04Ping\"\x06\n" +
	"\x04Pong\"\r\n" +
	"\vClientHello\"\x1f\n" +
	"\vCertificate\x12\x10\n" +
	"\x03der\x18\x01 \x01(\fR\x03derb\x06proto3"

var (
	file_protocol_proto_rawDescOnce sync.Once
	file_protocol_proto_rawDescData []byte
)

func file_protocol_proto_rawDescGZIP() []byte {
	file_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)))
	})
	return file_protocol_proto_rawDescData
}

var file_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protocol_proto_goTypes = []any{
	(*ServerToClient)(nil), // 0: rc.x509.protocol.v1.ServerToClient
	(*ClientToServer)(nil), // 1: rc.x509.protocol.v1.ClientToServer
	(*Ping)(nil),           // 2: rc.x509.protocol.v1.Ping
	(*Pong)(nil),           // 3: rc.x509.protocol.v1.Pong
	(*ClientHello)(nil),    // 4: rc.x509.protocol.v1.ClientHello
	(*Certificate)(nil),    // 5: rc.x509.protocol.v1.Certificate
}
var file_protocol_proto_depIdxs = []int32{
	2, // 0: rc.x509.protocol.v1.ServerToClient.ping:type_name -> rc.x509.protocol.v1.Ping
	5, // 1: rc.x509.protocol.v1.ServerToClient.certificate_push:type_name -> rc.x509.protocol.v1.Certificate
	3, // 2: rc.x509.protocol.v1.ClientToServer.pong:type_name -> rc.x509.protocol.v1.Pong
	4, // 3: rc.x509.protocol.v1.ClientToServer.client_hello:type_name -> rc.x509.protocol.v1.ClientHello
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protocol_proto_init() }
func file_protocol_proto_init() {
	if File_protocol_proto != nil {
		return
	}
	file_protocol_proto_msgTypes[0].OneofWrappers = []any{
		(*ServerToClient_Ping)(nil),
		(*ServerToClient_CertificatePush)(nil),
	}
	file_protocol_proto_msgTypes[1].OneofWrappers = []any{
		(*ClientToServer_Pong)(nil),
		(*ClientToServer_ClientHello)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_proto_depIdxs,
		MessageInfos:      file_protocol_proto_msgTypes,
	}.Build()
	File_protocol_proto = out.File
	file_protocol_proto_goTypes = nil
	file_protocol_proto_depIdxs = nil
}
