/* Copyright 2026 Datadog, Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * libdd-rc - Remote Configuration Client Library
 *
 * C FFI interface for the Datadog Remote Configuration X509 client library.
 */


#ifndef LIBDD_RC_H
#define LIBDD_RC_H

/* Warning: This file is autogenerated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/*
 Result of pushing data received from the RC delivery backend into the
 internal client library recv queue (returned by the client library).
 */
enum recv_ret_t {
    /*
     The message was successfully passed.
     */
    RECV_RET_T_SUCCESS = 0,
    RECV_RET_T_QUEUE_FULL = 1,
};
typedef int32_t recv_ret_t;

/*
 Result of sending data to the RC delivery backend, returned by the host
 runtime.
 */
enum send_ret_t {
    SEND_RET_T_SUCCESS = 0,
    SEND_RET_T_CLOSED = 1,
    SEND_RET_T_QUEUE_FULL = 2,
    SEND_RET_T_UNKNOWN = INT32_MAX,
};
typedef int32_t send_ret_t;

/*
 A [`Ctx`] is a RAII handle for an instance of a X509 verifier.

 The [`Ctx`] owns the event loop / runtime that drives the internal client
 execution, and owns caches of state (certificates, CRLs, etc) which are
 shared across all connections to the RC delivery backend.

 Each [`Ctx`] spawns a worker thread, and can have zero or more
 [`FFIConnection`] registered to it to provide I/O and manage per-connection
 state.

 The FFI host is responsible for constructing a [`Ctx`] with [`rc_init()`],
 and shutting down the [`Ctx`] with [`rc_free()`] to release all resources it
 holds.

 [`FFIConnection`]: super::FFIConnection
 */
typedef struct Ctx Ctx;

/*
 An [`FFIConnection`] brokers I/O between the client library and the FFI host
 runtime, modelling a single connection to the RC backend.

 One [`FFIConnection`] directly maps to one RC backend platform session,
 where "session" is typically a single WebSocket connection.

 The [`FFIConnection`] holds per-connection state, and is registered to a
 [`Ctx`] by the host runtime. The connection to the RC backend is managed by
 the host runtime, and connection lifecycle events are communicated to the
 client library by calling FFI functions with the appropriate
 [`FFIConnection`] handle.

 This type is represented across the FFI boundary as an [opaque handle]; the
 host runtime can reference the handle when making subsequent FFI functions,
 but cannot interact with the internal fields.

 [opaque handle]: https://interrupt.memfault.com/blog/opaque-pointers
 */
typedef struct FFIConnection FFIConnection;

/*
 Send `data` from the client library to the RC delivery backend over the
 network [`FFIConnection`] the callback was registered to..

 Passes a reference to a byte slice of `length` number of bytes that is valid
 for the lifetime of the function call.

   * Called by: `client library`.
   * Ownership: passes shared reference to the `data` array to the host
     runtime for the duration of the call.

 NOTE: the client library retains ownership of `data` after this call, and it
 may be freed or modified at any time after this function returns.
 */
typedef send_ret_t (*SendCb)(const uint8_t *data, int32_t length);

/*
 Mark the connection as established.

 The caller MUST have made a previous call to [`rc_set_send_callback`],
 else this call will return an error and the connection will not be
 marked as available internally.

   * Called by: `host runtime`.
   * Ownership: passes mutable reference of [`FFIConnection`] to client
     library for the duration of the call.

 */
void rc_conn_connected(struct FFIConnection *conn);

/*
 Mark the connection as closed.

 The caller MUST NOT call [`rc_conn_recv()`] for this `conn` after this
 call, but MAY subsequently call [`rc_conn_connected()`] for the same
 `conn` to resume communication.

   * Called by: `host runtime`.
   * Ownership: passes mutable reference of [`FFIConnection`] to client
     library for the duration of the call.

 */
void rc_conn_disconnected(struct FFIConnection *conn);

/*
 Pass data received from the RC delivery backend for the `conn`
 connection.

   * Called by: `host runtime`.
   * Ownership: passes shared reference of [`FFIConnection`] and `data`
     to client library for the duration of the call.

 NOTE: the host runtime retains ownership of `data` after this call, and
 is responsible for freeing the memory backing it after this call
 completes.
 */
recv_ret_t rc_conn_recv(const struct FFIConnection *conn, const uint8_t *data, int32_t length);

/*
 Release the resources held by this `conn`.

   * Called by: `host runtime`.
   * Ownership: passes ownership of [`FFIConnection`] to client library.

 */
void rc_conn_free(struct FFIConnection *conn);

/*
 Initialise a new client connection state.

   * Called by: `host runtime`.
   * Ownership: passes mutable reference of `conn` for the duration of the
     call, and returns ownership of [`FFIConnection`].

 */
struct FFIConnection *rc_conn_new(struct Ctx *ctx);

/*
 Configure the callback used by the client library to request data be sent to
 the RC backend.

 This call MUST be made before the first call to [`rc_conn_connected()`] for
 the same `conn`.

   * Called by: `host runtime`.
   * Ownership: passes mutable reference of `conn` for the duration of the
     call.

 */
void rc_set_send_callback(struct FFIConnection *conn, SendCb cb);

/*
 Initialise a new client [`Ctx`], starting a background thread to drive
 internal execution.

   * Called by: `host runtime`.
   * Ownership: returns ownership of [`Ctx`] to host runtime.

 */
struct Ctx *rc_init(void);

/*
 Stop the client running in [`Ctx`], and release all resources held by
 [`Ctx`].

 Callers MUST have previously disconnected ([`rc_conn_disconnected()`]) any
 open connections and released ([`rc_conn_free()`]) any connections held by
 the caller prior to calling this function.

   * Called by: `host runtime`.
   * Ownership: passes ownership of [`Ctx`] to client library.

 [`rc_conn_disconnected()`]: super::rc_conn_disconnected()
 [`rc_conn_free()`]: super::rc_conn_free()
 */
void rc_free(struct Ctx *ctx);

#endif  /* LIBDD_RC_H */
