/* Copyright 2026-Present Datadog, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * libdd-rc - Remote Configuration Client Library Test Harness
 *
 * C FFI interface for testing the Datadog Remote Configuration X509 client library.
 */

#include "libdd_rc.h"


#ifndef LIBDD_RC_TEST_HARNESS_H
#define LIBDD_RC_TEST_HARNESS_H

/* Warning: This file is autogenerated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/*
 Initialise test [`Ctx`] with echo entrypoint for testing.

 Echo entrypoint respond with Pong to all messages. Good for test FFI layer.

   * Called by: `test code`.
   * Ownership: returns ownership of [`Ctx`] to caller.

 # Safety

 This call is always safe.
 */
Ctx *rc_init_test(void);

#endif  /* LIBDD_RC_TEST_HARNESS_H */
