// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protocol.proto

// This package provides the core protocol types used "on the wire" between the
// Remote Config backend delivery servers, and a Datadog Agent (or other clients
// of RC).

package rcproto

import (
	magic_tunnel "github.com/DataDog/libdd-rc/ffi-hosts/go/rcproto/magic_tunnel"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Error conditions for the transport & dispatch logic.
//
// These errors describe the possible failure modes of delivering the request
// and invoking the registered handler for the payload type.
type DispatchResponse_DispatchError int32

const (
	DispatchResponse_DISPATCH_ERROR_UNSPECIFIED DispatchResponse_DispatchError = 0
	// The client does not support the payload type being dispatched.
	DispatchResponse_DISPATCH_ERROR_UNKNOWN_PAYLOAD DispatchResponse_DispatchError = 1
	// The client supports the type of payload being sent, but there is no
	// handler registered to process it.
	DispatchResponse_DISPATCH_ERROR_NO_DISPATCH_HANDLER DispatchResponse_DispatchError = 2
	// The dispatch handler delivery queue is full.
	//
	// This occurs when the dispatch handler is not consuming messages fast
	// enough to keep up with the rate of new requests arriving. The message
	// will not be delivered.
	DispatchResponse_DISPATCH_ERROR_QUEUE_FULL DispatchResponse_DispatchError = 3
)

// Enum value maps for DispatchResponse_DispatchError.
var (
	DispatchResponse_DispatchError_name = map[int32]string{
		0: "DISPATCH_ERROR_UNSPECIFIED",
		1: "DISPATCH_ERROR_UNKNOWN_PAYLOAD",
		2: "DISPATCH_ERROR_NO_DISPATCH_HANDLER",
		3: "DISPATCH_ERROR_QUEUE_FULL",
	}
	DispatchResponse_DispatchError_value = map[string]int32{
		"DISPATCH_ERROR_UNSPECIFIED":         0,
		"DISPATCH_ERROR_UNKNOWN_PAYLOAD":     1,
		"DISPATCH_ERROR_NO_DISPATCH_HANDLER": 2,
		"DISPATCH_ERROR_QUEUE_FULL":          3,
	}
)

func (x DispatchResponse_DispatchError) Enum() *DispatchResponse_DispatchError {
	p := new(DispatchResponse_DispatchError)
	*p = x
	return p
}

func (x DispatchResponse_DispatchError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DispatchResponse_DispatchError) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_proto_enumTypes[0].Descriptor()
}

func (DispatchResponse_DispatchError) Type() protoreflect.EnumType {
	return &file_protocol_proto_enumTypes[0]
}

func (x DispatchResponse_DispatchError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DispatchResponse_DispatchError.Descriptor instead.
func (DispatchResponse_DispatchError) EnumDescriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{7, 0}
}

// Messages from the RC backend server, to an RC client.
type ServerToClient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerToClient_Ping
	//	*ServerToClient_CertificatePush
	//	*ServerToClient_Dispatch
	Message       isServerToClient_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerToClient) Reset() {
	*x = ServerToClient{}
	mi := &file_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerToClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerToClient) ProtoMessage() {}

func (x *ServerToClient) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerToClient.ProtoReflect.Descriptor instead.
func (*ServerToClient) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *ServerToClient) GetMessage() isServerToClient_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerToClient) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Message.(*ServerToClient_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ServerToClient) GetCertificatePush() *Certificate {
	if x != nil {
		if x, ok := x.Message.(*ServerToClient_CertificatePush); ok {
			return x.CertificatePush
		}
	}
	return nil
}

func (x *ServerToClient) GetDispatch() *DispatchRequest {
	if x != nil {
		if x, ok := x.Message.(*ServerToClient_Dispatch); ok {
			return x.Dispatch
		}
	}
	return nil
}

type isServerToClient_Message interface {
	isServerToClient_Message()
}

type ServerToClient_Ping struct {
	Ping *Ping `protobuf:"bytes,1,opt,name=ping,proto3,oneof"`
}

type ServerToClient_CertificatePush struct {
	// The server is pushing a new X509 certificate to the client to consider
	// when chain building.
	//
	// This certificate MUST be treated as an untrusted input.
	CertificatePush *Certificate `protobuf:"bytes,2,opt,name=certificate_push,json=certificatePush,proto3,oneof"`
}

type ServerToClient_Dispatch struct {
	// Pass a message to the host application.
	Dispatch *DispatchRequest `protobuf:"bytes,3,opt,name=dispatch,proto3,oneof"`
}

func (*ServerToClient_Ping) isServerToClient_Message() {}

func (*ServerToClient_CertificatePush) isServerToClient_Message() {}

func (*ServerToClient_Dispatch) isServerToClient_Message() {}

// Messages from an RC client, to the RC backend server.
type ClientToServer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ClientToServer_Pong
	//	*ClientToServer_ClientHello
	//	*ClientToServer_Dispatch
	Message       isClientToServer_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientToServer) Reset() {
	*x = ClientToServer{}
	mi := &file_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientToServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientToServer) ProtoMessage() {}

func (x *ClientToServer) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientToServer.ProtoReflect.Descriptor instead.
func (*ClientToServer) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *ClientToServer) GetMessage() isClientToServer_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ClientToServer) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Message.(*ClientToServer_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *ClientToServer) GetClientHello() *ClientHello {
	if x != nil {
		if x, ok := x.Message.(*ClientToServer_ClientHello); ok {
			return x.ClientHello
		}
	}
	return nil
}

func (x *ClientToServer) GetDispatch() *DispatchResponse {
	if x != nil {
		if x, ok := x.Message.(*ClientToServer_Dispatch); ok {
			return x.Dispatch
		}
	}
	return nil
}

type isClientToServer_Message interface {
	isClientToServer_Message()
}

type ClientToServer_Pong struct {
	Pong *Pong `protobuf:"bytes,1,opt,name=pong,proto3,oneof"`
}

type ClientToServer_ClientHello struct {
	// The opening message sent when establishing a new connection.
	ClientHello *ClientHello `protobuf:"bytes,2,opt,name=client_hello,json=clientHello,proto3,oneof"`
}

type ClientToServer_Dispatch struct {
	// Respond with the return value from a dispatch call.
	Dispatch *DispatchResponse `protobuf:"bytes,3,opt,name=dispatch,proto3,oneof"`
}

func (*ClientToServer_Pong) isClientToServer_Message() {}

func (*ClientToServer_ClientHello) isClientToServer_Message() {}

func (*ClientToServer_Dispatch) isClientToServer_Message() {}

// An application-level ping message. Each `Ping` generates exactly one `Pong`.
//
// While the WebSocket transport to the RC delivery backend has a transport
// level "ping" control frame, it doesn't capture the full end-to-end delivery
// path as it never transits through the client library.
//
// This application-level ping frame arrives as a standard message to the client
// library, and transits through the FFI layer in addition to the WebSocket
// transport.
//
// This message is useful for ensuring the client is still alive, in addition to
// the WebSocket connection.
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{2}
}

// The response to a `Ping` message from the server.
type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{3}
}

type ClientHello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique, sequential connection ID assigned to this logical client
	// connection (starting value: 0);
	//
	// This value persists for the lifetime of a logical client connection, each
	// of which may experience multiple reconnection events. This value increases
	// only when multiple connections are created by the host runtime (calls to
	// `rc_conn_new()`).
	ConnectionId uint64 `protobuf:"varint,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// The number of times this logical connection has been gracefully
	// disconnected from the RC backend by the RC server (per-`connection_id`,
	// starting value: 0).
	GracefulDisconnectionCount uint64 `protobuf:"varint,2,opt,name=graceful_disconnection_count,json=gracefulDisconnectionCount,proto3" json:"graceful_disconnection_count,omitempty"`
	// The number of times this logical connection has been forcibly /
	// ungracefully disconnected from the RC backend (per-`connection_id`,
	// starting value: 0).
	UngracefulDisconnectionCount uint64 `protobuf:"varint,3,opt,name=ungraceful_disconnection_count,json=ungracefulDisconnectionCount,proto3" json:"ungraceful_disconnection_count,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *ClientHello) GetConnectionId() uint64 {
	if x != nil {
		return x.ConnectionId
	}
	return 0
}

func (x *ClientHello) GetGracefulDisconnectionCount() uint64 {
	if x != nil {
		return x.GracefulDisconnectionCount
	}
	return 0
}

func (x *ClientHello) GetUngracefulDisconnectionCount() uint64 {
	if x != nil {
		return x.UngracefulDisconnectionCount
	}
	return 0
}

// An X509 certificate as raw DER-encoded bytes.
type Certificate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Der           []byte                 `protobuf:"bytes,1,opt,name=der,proto3" json:"der,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Certificate) Reset() {
	*x = Certificate{}
	mi := &file_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate) ProtoMessage() {}

func (x *Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certificate.ProtoReflect.Descriptor instead.
func (*Certificate) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *Certificate) GetDer() []byte {
	if x != nil {
		return x.Der
	}
	return nil
}

// Instruct the client library to deliver a payload to the host application.
//
// Dispatch requests are expected to map one-to-one with `DispatchResponse`,
// which returns the result of the dispatch call asynchronously.
type DispatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An identifier to correlate any response with this request.
	//
	// The only guarantee provided by a `correlation_id` is that it is unique per
	// connection.
	CorrelationId uint64 `protobuf:"varint,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// The signature over the "encoded_dispatch_request" buffer.
	Signature *DetachedSignature `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// The protobuf-serialised DispatchRequestPayload that "signature" covers.
	EncodedDispatchRequest []byte `protobuf:"bytes,3,opt,name=encoded_dispatch_request,json=encodedDispatchRequest,proto3" json:"encoded_dispatch_request,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	mi := &file_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *DispatchRequest) GetCorrelationId() uint64 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *DispatchRequest) GetSignature() *DetachedSignature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *DispatchRequest) GetEncodedDispatchRequest() []byte {
	if x != nil {
		return x.EncodedDispatchRequest
	}
	return nil
}

// A response to the `DispatchRequest` uniquely identified by the
// `correlation_id`.
type DispatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The `correlation_id` value sent in the `DispatchRequest`.
	CorrelationId uint64 `protobuf:"varint,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*DispatchResponse_Error
	//	*DispatchResponse_Payload
	Result        isDispatchResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchResponse) Reset() {
	*x = DispatchResponse{}
	mi := &file_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchResponse) ProtoMessage() {}

func (x *DispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchResponse.ProtoReflect.Descriptor instead.
func (*DispatchResponse) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *DispatchResponse) GetCorrelationId() uint64 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *DispatchResponse) GetResult() isDispatchResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *DispatchResponse) GetError() DispatchResponse_DispatchError {
	if x != nil {
		if x, ok := x.Result.(*DispatchResponse_Error); ok {
			return x.Error
		}
	}
	return DispatchResponse_DISPATCH_ERROR_UNSPECIFIED
}

func (x *DispatchResponse) GetPayload() *DispatchResponsePayload {
	if x != nil {
		if x, ok := x.Result.(*DispatchResponse_Payload); ok {
			return x.Payload
		}
	}
	return nil
}

type isDispatchResponse_Result interface {
	isDispatchResponse_Result()
}

type DispatchResponse_Error struct {
	Error DispatchResponse_DispatchError `protobuf:"varint,2,opt,name=error,proto3,enum=rc.x509.protocol.v1.DispatchResponse_DispatchError,oneof"`
}

type DispatchResponse_Payload struct {
	Payload *DispatchResponsePayload `protobuf:"bytes,3,opt,name=payload,proto3,oneof"`
}

func (*DispatchResponse_Error) isDispatchResponse_Result() {}

func (*DispatchResponse_Payload) isDispatchResponse_Result() {}

// The signed request payload of a Dispatch call.
type DispatchRequestPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The connection ID this message is targetted to.
	//
	// The client MUST validate this connection_id matches the expected value
	// before any processing of the payload. The client SHOULD disconnect if this
	// value differs from the expected value as an indicator of an ongoing MITM.
	ConnectionId *ConnectionId `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*DispatchRequestPayload_MagicTunnel
	Payload       isDispatchRequestPayload_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchRequestPayload) Reset() {
	*x = DispatchRequestPayload{}
	mi := &file_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequestPayload) ProtoMessage() {}

func (x *DispatchRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequestPayload.ProtoReflect.Descriptor instead.
func (*DispatchRequestPayload) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *DispatchRequestPayload) GetConnectionId() *ConnectionId {
	if x != nil {
		return x.ConnectionId
	}
	return nil
}

func (x *DispatchRequestPayload) GetPayload() isDispatchRequestPayload_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DispatchRequestPayload) GetMagicTunnel() *magic_tunnel.MagicTunnelRequest {
	if x != nil {
		if x, ok := x.Payload.(*DispatchRequestPayload_MagicTunnel); ok {
			return x.MagicTunnel
		}
	}
	return nil
}

type isDispatchRequestPayload_Payload interface {
	isDispatchRequestPayload_Payload()
}

type DispatchRequestPayload_MagicTunnel struct {
	MagicTunnel *magic_tunnel.MagicTunnelRequest `protobuf:"bytes,2,opt,name=magic_tunnel,json=magicTunnel,proto3,oneof"`
}

func (*DispatchRequestPayload_MagicTunnel) isDispatchRequestPayload_Payload() {}

// The response payload of a successful Dispatch call.
type DispatchResponsePayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*DispatchResponsePayload_MagicTunnel
	Payload       isDispatchResponsePayload_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchResponsePayload) Reset() {
	*x = DispatchResponsePayload{}
	mi := &file_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchResponsePayload) ProtoMessage() {}

func (x *DispatchResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchResponsePayload.ProtoReflect.Descriptor instead.
func (*DispatchResponsePayload) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *DispatchResponsePayload) GetPayload() isDispatchResponsePayload_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DispatchResponsePayload) GetMagicTunnel() *magic_tunnel.MagicTunnelResponse {
	if x != nil {
		if x, ok := x.Payload.(*DispatchResponsePayload_MagicTunnel); ok {
			return x.MagicTunnel
		}
	}
	return nil
}

type isDispatchResponsePayload_Payload interface {
	isDispatchResponsePayload_Payload()
}

type DispatchResponsePayload_MagicTunnel struct {
	MagicTunnel *magic_tunnel.MagicTunnelResponse `protobuf:"bytes,1,opt,name=magic_tunnel,json=magicTunnel,proto3,oneof"`
}

func (*DispatchResponsePayload_MagicTunnel) isDispatchResponsePayload_Payload() {}

// A globally unique identifier for the active connection.
type ConnectionId struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A [UUID Version 8] encoded as a raw [big-endian byte sequence].
	//
	// [big-endian byte sequence]: https://datatracker.ietf.org/doc/html/rfc9562#name-uuid-format
	// [UUID Version 8]: https://datatracker.ietf.org/doc/html/rfc9562#name-uuid-version-8
	UuidV8        []byte `protobuf:"bytes,1,opt,name=uuid_v8,json=uuidV8,proto3" json:"uuid_v8,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionId) Reset() {
	*x = ConnectionId{}
	mi := &file_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionId) ProtoMessage() {}

func (x *ConnectionId) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionId.ProtoReflect.Descriptor instead.
func (*ConnectionId) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *ConnectionId) GetUuidV8() []byte {
	if x != nil {
		return x.UuidV8
	}
	return nil
}

var File_protocol_proto protoreflect.FileDescriptor

const file_protocol_proto_rawDesc = "" +
	"\n" +
	"\x0eprotocol.proto\x12\x13rc.x509.protocol.v1\x1a\x1bmagic_tunnel/protocol.proto\x1a\x0fsignature.proto\"\xdf\x01\n" +
	"\x0eServerToClient\x12/\n" +
	"\x04ping\x18\x01 \x01(\v2\x19.rc.x509.protocol.v1.PingH\x00R\x04ping\x12M\n" +
	"\x10certificate_push\x18\x02 \x01(\v2 .rc.x509.protocol.v1.CertificateH\x00R\x0fcertificatePush\x12B\n" +
	"\bdispatch\x18\x03 \x01(\v2$.rc.x509.protocol.v1.DispatchRequestH\x00R\bdispatchB\t\n" +
	"\amessage\"\xd8\x01\n" +
	"\x0eClientToServer\x12/\n" +
	"\x04pong\x18\x01 \x01(\v2\x19.rc.x509.protocol.v1.PongH\x00R\x04pong\x12E\n" +
	"\fclient_hello\x18\x02 \x01(\v2 .rc.x509.protocol.v1.ClientHelloH\x00R\vclientHello\x12C\n" +
	"\bdispatch\x18\x03 \x01(\v2%.rc.x509.protocol.v1.DispatchResponseH\x00R\bdispatchB\t\n" +
	"\amessage\"\x06\n" +
	"\x04Ping\"\x06\n" +
	"\x04Pong\"\xba\x01\n" +
	"\vClientHello\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\x04R\fconnectionId\x12@\n" +
	"\x1cgraceful_disconnection_count\x18\x02 \x01(\x04R\x1agracefulDisconnectionCount\x12D\n" +
	"\x1eungraceful_disconnection_count\x18\x03 \x01(\x04R\x1cungracefulDisconnectionCount\"\x1f\n" +
	"\vCertificate\x12\x10\n" +
	"\x03der\x18\x01 \x01(\fR\x03der\"\xb9\x01\n" +
	"\x0fDispatchRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\x04R\rcorrelationId\x12E\n" +
	"\tsignature\x18\x02 \x01(\v2'.rc.x509.signature.v1.DetachedSignatureR\tsignature\x128\n" +
	"\x18encoded_dispatch_request\x18\x03 \x01(\fR\x16encodedDispatchRequest\"\xf7\x02\n" +
	"\x10DispatchResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\x04R\rcorrelationId\x12K\n" +
	"\x05error\x18\x02 \x01(\x0e23.rc.x509.protocol.v1.DispatchResponse.DispatchErrorH\x00R\x05error\x12H\n" +
	"\apayload\x18\x03 \x01(\v2,.rc.x509.protocol.v1.DispatchResponsePayloadH\x00R\apayload\"\x9a\x01\n" +
	"\rDispatchError\x12\x1e\n" +
	"\x1aDISPATCH_ERROR_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eDISPATCH_ERROR_UNKNOWN_PAYLOAD\x10\x01\x12&\n" +
	"\"DISPATCH_ERROR_NO_DISPATCH_HANDLER\x10\x02\x12\x1d\n" +
	"\x19DISPATCH_ERROR_QUEUE_FULL\x10\x03B\b\n" +
	"\x06result\"\xbd\x01\n" +
	"\x16DispatchRequestPayload\x12F\n" +
	"\rconnection_id\x18\x01 \x01(\v2!.rc.x509.protocol.v1.ConnectionIdR\fconnectionId\x12P\n" +
	"\fmagic_tunnel\x18\x02 \x01(\v2+.rc.x509.magic_tunnel.v1.MagicTunnelRequestH\x00R\vmagicTunnelB\t\n" +
	"\apayload\"w\n" +
	"\x17DispatchResponsePayload\x12Q\n" +
	"\fmagic_tunnel\x18\x01 \x01(\v2,.rc.x509.magic_tunnel.v1.MagicTunnelResponseH\x00R\vmagicTunnelB\t\n" +
	"\apayload\"'\n" +
	"\fConnectionId\x12\x17\n" +
	"\auuid_v8\x18\x01 \x01(\fR\x06uuidV8B:Z8github.com/DataDog/libdd-rc/ffi-hosts/go/rcproto;rcprotob\x06proto3"

var (
	file_protocol_proto_rawDescOnce sync.Once
	file_protocol_proto_rawDescData []byte
)

func file_protocol_proto_rawDescGZIP() []byte {
	file_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)))
	})
	return file_protocol_proto_rawDescData
}

var file_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_protocol_proto_goTypes = []any{
	(DispatchResponse_DispatchError)(0),      // 0: rc.x509.protocol.v1.DispatchResponse.DispatchError
	(*ServerToClient)(nil),                   // 1: rc.x509.protocol.v1.ServerToClient
	(*ClientToServer)(nil),                   // 2: rc.x509.protocol.v1.ClientToServer
	(*Ping)(nil),                             // 3: rc.x509.protocol.v1.Ping
	(*Pong)(nil),                             // 4: rc.x509.protocol.v1.Pong
	(*ClientHello)(nil),                      // 5: rc.x509.protocol.v1.ClientHello
	(*Certificate)(nil),                      // 6: rc.x509.protocol.v1.Certificate
	(*DispatchRequest)(nil),                  // 7: rc.x509.protocol.v1.DispatchRequest
	(*DispatchResponse)(nil),                 // 8: rc.x509.protocol.v1.DispatchResponse
	(*DispatchRequestPayload)(nil),           // 9: rc.x509.protocol.v1.DispatchRequestPayload
	(*DispatchResponsePayload)(nil),          // 10: rc.x509.protocol.v1.DispatchResponsePayload
	(*ConnectionId)(nil),                     // 11: rc.x509.protocol.v1.ConnectionId
	(*DetachedSignature)(nil),                // 12: rc.x509.signature.v1.DetachedSignature
	(*magic_tunnel.MagicTunnelRequest)(nil),  // 13: rc.x509.magic_tunnel.v1.MagicTunnelRequest
	(*magic_tunnel.MagicTunnelResponse)(nil), // 14: rc.x509.magic_tunnel.v1.MagicTunnelResponse
}
var file_protocol_proto_depIdxs = []int32{
	3,  // 0: rc.x509.protocol.v1.ServerToClient.ping:type_name -> rc.x509.protocol.v1.Ping
	6,  // 1: rc.x509.protocol.v1.ServerToClient.certificate_push:type_name -> rc.x509.protocol.v1.Certificate
	7,  // 2: rc.x509.protocol.v1.ServerToClient.dispatch:type_name -> rc.x509.protocol.v1.DispatchRequest
	4,  // 3: rc.x509.protocol.v1.ClientToServer.pong:type_name -> rc.x509.protocol.v1.Pong
	5,  // 4: rc.x509.protocol.v1.ClientToServer.client_hello:type_name -> rc.x509.protocol.v1.ClientHello
	8,  // 5: rc.x509.protocol.v1.ClientToServer.dispatch:type_name -> rc.x509.protocol.v1.DispatchResponse
	12, // 6: rc.x509.protocol.v1.DispatchRequest.signature:type_name -> rc.x509.signature.v1.DetachedSignature
	0,  // 7: rc.x509.protocol.v1.DispatchResponse.error:type_name -> rc.x509.protocol.v1.DispatchResponse.DispatchError
	10, // 8: rc.x509.protocol.v1.DispatchResponse.payload:type_name -> rc.x509.protocol.v1.DispatchResponsePayload
	11, // 9: rc.x509.protocol.v1.DispatchRequestPayload.connection_id:type_name -> rc.x509.protocol.v1.ConnectionId
	13, // 10: rc.x509.protocol.v1.DispatchRequestPayload.magic_tunnel:type_name -> rc.x509.magic_tunnel.v1.MagicTunnelRequest
	14, // 11: rc.x509.protocol.v1.DispatchResponsePayload.magic_tunnel:type_name -> rc.x509.magic_tunnel.v1.MagicTunnelResponse
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_protocol_proto_init() }
func file_protocol_proto_init() {
	if File_protocol_proto != nil {
		return
	}
	file_signature_proto_init()
	file_protocol_proto_msgTypes[0].OneofWrappers = []any{
		(*ServerToClient_Ping)(nil),
		(*ServerToClient_CertificatePush)(nil),
		(*ServerToClient_Dispatch)(nil),
	}
	file_protocol_proto_msgTypes[1].OneofWrappers = []any{
		(*ClientToServer_Pong)(nil),
		(*ClientToServer_ClientHello)(nil),
		(*ClientToServer_Dispatch)(nil),
	}
	file_protocol_proto_msgTypes[7].OneofWrappers = []any{
		(*DispatchResponse_Error)(nil),
		(*DispatchResponse_Payload)(nil),
	}
	file_protocol_proto_msgTypes[8].OneofWrappers = []any{
		(*DispatchRequestPayload_MagicTunnel)(nil),
	}
	file_protocol_proto_msgTypes[9].OneofWrappers = []any{
		(*DispatchResponsePayload_MagicTunnel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_proto_depIdxs,
		EnumInfos:         file_protocol_proto_enumTypes,
		MessageInfos:      file_protocol_proto_msgTypes,
	}.Build()
	File_protocol_proto = out.File
	file_protocol_proto_goTypes = nil
	file_protocol_proto_depIdxs = nil
}
