// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: signature.proto

// The signature structure used by the X509 platform.

package rcproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A DetachedSignature combines a cryptographic signature with the metadata
// necessary verify it.
type DetachedSignature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Subject Key Identifier (SKI) of the signing certificate.
	//
	// This is the raw SKI value extracted from the certificate's Subject Key
	// Identifier extension, as defined in [RFC 5280 § 4.2.1.2]. It corresponds
	// to the `CertId` type in rc-crypto.
	//
	// This is an untrusted value: the cert issuer may set it to anything, and it
	// does not necessarily represent a cryptographic hash of the key material
	// (e.g. `hash(cert_dn + cert_serial)` is not uncommon in practice).
	//
	// [RFC 5280 § 4.2.1.2]:
	//
	//	https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.2
	CertId []byte `protobuf:"bytes,1,opt,name=cert_id,json=certId,proto3" json:"cert_id,omitempty"`
	// A signature over the signed payload.
	//
	// This signature is a variable length ASN.1 DER-encoded Ecdsa-Sig-Value as
	// defined in [RFC 3279 § 2.2.3], but utilising SHA-256 as the internal
	// cryptographic hash.
	//
	// [RFC 3279 § 2.2.3]: https://tools.ietf.org/html/rfc3279#section-2.2.3
	Signature     []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachedSignature) Reset() {
	*x = DetachedSignature{}
	mi := &file_signature_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachedSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachedSignature) ProtoMessage() {}

func (x *DetachedSignature) ProtoReflect() protoreflect.Message {
	mi := &file_signature_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachedSignature.ProtoReflect.Descriptor instead.
func (*DetachedSignature) Descriptor() ([]byte, []int) {
	return file_signature_proto_rawDescGZIP(), []int{0}
}

func (x *DetachedSignature) GetCertId() []byte {
	if x != nil {
		return x.CertId
	}
	return nil
}

func (x *DetachedSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_signature_proto protoreflect.FileDescriptor

const file_signature_proto_rawDesc = "" +
	"\n" +
	"\x0fsignature.proto\x12\x14rc.x509.signature.v1\"J\n" +
	"\x11DetachedSignature\x12\x17\n" +
	"\acert_id\x18\x01 \x01(\fR\x06certId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignatureB:Z8github.com/DataDog/libdd-rc/ffi-hosts/go/rcproto;rcprotob\x06proto3"

var (
	file_signature_proto_rawDescOnce sync.Once
	file_signature_proto_rawDescData []byte
)

func file_signature_proto_rawDescGZIP() []byte {
	file_signature_proto_rawDescOnce.Do(func() {
		file_signature_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signature_proto_rawDesc), len(file_signature_proto_rawDesc)))
	})
	return file_signature_proto_rawDescData
}

var file_signature_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_signature_proto_goTypes = []any{
	(*DetachedSignature)(nil), // 0: rc.x509.signature.v1.DetachedSignature
}
var file_signature_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_signature_proto_init() }
func file_signature_proto_init() {
	if File_signature_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signature_proto_rawDesc), len(file_signature_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_signature_proto_goTypes,
		DependencyIndexes: file_signature_proto_depIdxs,
		MessageInfos:      file_signature_proto_msgTypes,
	}.Build()
	File_signature_proto = out.File
	file_signature_proto_goTypes = nil
	file_signature_proto_depIdxs = nil
}
