# Copyright 2026-Present Datadog, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Ensure protobuf changes are backwards compatible.
#
# Uses https://github.com/bufbuild/buf (also available as a vscode extension).
#
# Run locally with:
#
#  * buf lint
#  * buf format -w
#  * buf breaking --against https://github.com/DataDog/libdd-rc.git#branch=main
#
# Adding the "breaking-proto" label to a PR allows the breaking changes to be
# merged, bypassing the "breaking" gate (but not the "lint" check).

name: buf
permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  merge_group:
  push:
    branches: [main]

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - uses: bufbuild/buf-action@fd21066df7214747548607aaa45548ba2b9bc1ff # v1.4.0
        id: buf
        with:
          lint: true
          format: true
          breaking: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'breaking-proto') }}
          push: false
          archive: false
          pr_comment: false
          github_token: ${{ secrets.GITHUB_TOKEN }} # Private repo access

      - name: Bypass message
        if: failure() && steps.buf.outcome == 'failure'
        run: |
          echo "::error::Add the breaking-proto label to the PR to allow breaking changes to be merged."
          exit 1
