# Copyright 2026-Present Datadog, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file ensures the repo has up-to-date legal notices.
#
# See "docs/license.md" for helper script documentation.

name: licence
permissions:
  contents: read

on:
  workflow_call:
  pull_request:
  merge_group:
  push:
    branches: [main]

jobs:
  # All source code must have the Apache 2.0 header at the top.
  #
  # Configured by .licenserc.yaml at the repo root.
  check-headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      # https://github.com/apache/skywalking-eyes
      - name: Check Apache license headers
        uses: apache/skywalking-eyes/header@98a5d1362e26852204382ca749ed66631f15a95d
        with:
          mode: check

  # 3rd party crates must be listed in LICENSE-3rdparty.csv.
  check-3rdparty-bom:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/datadog/libdd-rc/rust-ci:1.93.0
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Check LICENSE-3rdparty.csv is up to date
        run: ./scripts/generate-3rdparty-licenses.sh check

  # 1st party crates have to be correctly licensed in their Cargo.toml
  check-1stparty-licenses:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/datadog/libdd-rc/rust-ci:1.93.0
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Check crate license fields
        run: ./scripts/check-1stparty-crate-licenses.sh
