# Copyright 2026-Present Datadog, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file ensures the repo has up-to-date legal notices.
#
# See "docs/license.md" for helper script documentation.

name: licence
permissions:
  contents: read

on:
  workflow_call:
  pull_request:
  merge_group:
  push:
    branches: [main]

jobs:
  # All source code must have the Apache 2.0 header at the top.
  #
  # Configured by .licenserc.yaml at the repo root.
  check-headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      # https://github.com/apache/skywalking-eyes
      - name: Check Apache license headers
        uses: apache/skywalking-eyes/header@98a5d1362e26852204382ca749ed66631f15a95d
        with:
          mode: check

  # 3rd party crates must be listed in LICENSE-3rdparty.csv.
  check-3rdparty-bom:
    runs-on: ubuntu-latest
    container:
      image: rust:1.93.0
    steps:
      - name: ensure node is installed for act
        if: ${{ env.ACT }}
        run: command -v node || (apt update && apt install -y nodejs zstd)

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Cache cargo-deny
        id: cache-cargo-deny
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: /usr/local/cargo/bin/cargo-deny
          key: ${{ runner.os }}-cargo-deny-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-deny

      # Manual install / not github action so scripts can be run to check after.
      - name: Install cargo-deny
        run: command -v cargo-deny || cargo install --git https://github.com/EmbarkStudios/cargo-deny --rev 8e63a579d8ac61faa6e00d3d4ecde495bf138540 cargo-deny # 0.19.0

      - name: Install jq
        run: apt-get update && apt-get install -y jq

      - name: Check LICENSE-3rdparty.csv is up to date
        run: ./scripts/generate-3rdparty-licenses.sh check

  # 1st party crates have to be correctly licensed in their Cargo.toml
  check-1stparty-licenses:
    runs-on: ubuntu-latest
    container:
      image: rust:1.93.0
    steps:
      - name: ensure node is installed for act
        if: ${{ env.ACT }}
        run: command -v node || (apt update && apt install -y nodejs zstd)

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Install jq
        run: apt-get update && apt-get install -y jq

      - name: Check crate license fields
        run: ./scripts/check-1stparty-crate-licenses.sh
