# Rust source code quality checks.

name: rust
permissions:
  contents: read

on:
  push:
    paths: &paths
      # This section defines when this CI will run:
      #
      # Be sure to update the crates miri is run against in the job itself if
      # adding new crates.
      - "rc-x509-client/src/host_runtime/ffi/**"
    branches:
      - main

  pull_request:
    paths: *paths
  merge_group:
    paths: *paths
  workflow_call:
    paths: *paths

env:
  # https://github.com/aws/aws-lc-rs/issues/569
  AWS_LC_FIPS_SYS_CC: clang

jobs:
  test-miri:
    runs-on: ubuntu-latest
    container:
      image: rustlang/rust:nightly # Miri is nightly only!
    steps:
      - name: Ensure node is installed for act
        if: ${{ env.ACT }}
        run: command -v node || (apt update && apt install -y nodejs zstd)

      - name: Install dependencies for aws-lc-rs
        run: apt-get update && apt-get install -y golang-go cmake clang

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Cache Rust dependencies
        id: rust-cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
        with:
          path: |
            target
            /usr/local/cargo/registry/index
            /usr/local/cargo/registry/cache
            /usr/local/cargo/git/db
          key: ${{ runner.os }}-cargo-miri-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-miri-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-miri-

      - name: install miri
        run: rustup +nightly component add miri

      - name: miri
        run: cargo +nightly miri test -p rc-x509-client ffi
