name: build

on:
  workflow_call:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - name: ensure node is installed for act
        if: ${{ env.ACT }}
        run: command -v node || (apt update && apt install -y nodejs zstd)

      - uses: actions/checkout@v4

      - name: Cache Rust dependencies
        id: rust-cache
        uses: actions/cache@v4
        with:
          path: |
            target
            /usr/local/cargo/registry/index
            /usr/local/cargo/registry/cache
            /usr/local/cargo/git/db
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-

      - name: dev
        id: build
        run: cargo build --workspace --all-features

      - name: release
        run: cargo build --workspace --all-features --release

      - name: benchmarks
        run: cargo test --workspace --all-features --benches --no-run

  clippy:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - name: ensure node is installed for act
        if: ${{ env.ACT }}
        run: command -v node || (apt update && apt install -y nodejs zstd)

      - uses: actions/checkout@v4

      - name: Cache Rust dependencies
        id: rust-cache
        uses: actions/cache@v4
        with:
          path: |
            target
            /usr/local/cargo/registry/index
            /usr/local/cargo/registry/cache
            /usr/local/cargo/git/db
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-

      - name: Install Clippy
        run: rustup component add clippy

      - name: Run Clippy
        run: cargo clippy --workspace --all-features --all-targets -- -D warnings

  test:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - name: ensure node is installed for act
        if: ${{ env.ACT }}
        run: command -v node || (apt update && apt install -y nodejs zstd)

      - uses: actions/checkout@v4

      - name: Cache Rust dependencies
        id: rust-cache
        uses: actions/cache@v4
        with:
          path: |
            target
            /usr/local/cargo/registry/index
            /usr/local/cargo/registry/cache
            /usr/local/cargo/git/db
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-

      - name: Run tests
        run: cargo test --workspace --all-features
