# Copyright 2026-Present Datadog, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Rust source code quality checks.

name: rust
permissions:
  contents: read

on:
  workflow_call:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  # https://github.com/aws/aws-lc-rs/issues/569
  AWS_LC_FIPS_SYS_CC: clang

jobs:
  check:
    strategy:
      matrix:
        include:
          - name: dev
            cmd: cargo build --workspace --all-features
          - name: release
            cmd: cargo build --workspace --all-features --release
          - name: benchmarks
            cmd: cargo test --workspace --all-features --benches --no-run
          - name: clippy
            cmd: cargo clippy --workspace --all-features -- -D warnings
          - name: test
            cmd: cargo test --workspace --all-features
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/datadog/libdd-rc/rust-ci:1.93.0
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup-rust
        with:
          cache-key-prefix: ${{ matrix.name }}

      - name: Install protoc-gen-go
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          echo "PROTOC_GEN_GO=$(go env GOPATH)/bin/protoc-gen-go" >> $GITHUB_ENV

      - name: ${{ matrix.name }}
        run: ${{ matrix.cmd }}

  # Check for banned crates, invalid sources, security advisories, and licenses
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - uses: EmbarkStudios/cargo-deny-action@3fd3802e88374d3fe9159b834c7714ec57d6c979 # v2.0.15
        with:
          arguments: --workspace
          command: check bans sources advisories licenses
